import { family } from '../../constants/font.jsx';

const styles = {
  modalContainer: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  backdrop: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    position: 'relative',
    width: '100%',
    height: '100%',
  },
  backdropHit: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    zIndex: 0,
  },
  panel: {
    width: '100%',
    maxWidth: 480,
    borderRadius: 24,
    padding: 18,
    boxSizing: 'border-box',
    borderWidth: '1px',
    borderStyle: 'solid',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    maxHeight: '80vh',
    position: 'relative',
    zIndex: 1,
  },
  titleRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: family.bold,
  },
  loadingIndicator: {
    fontSize: 14,
    fontFamily: family.bold,
  },
  tabsRowCentered: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  tabBtn: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 12,
    borderWidth: '1px',
    borderStyle: 'solid',
    cursor: 'pointer',
    background: 'transparent',
  },
  tabLabel: {
    fontSize: 13,
    fontFamily: family.bold,
  },
  listContainer: {
    flex: 1,
    minHeight: 200,
    maxHeight: '55vh',
    overflowY: 'auto',
    paddingLeft: 4,
    paddingRight: 4,
    WebkitOverflowScrolling: 'touch',
  },
};

export default styles;
